INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'malisha', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'malisha', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'malisha', 'Get GCP Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'malisha', 'Get DevOps', CURRENT_DATE(), false);
